exports.list = [
  "People who look at me are guilty of lust",
  "Herpes? I already have herpes!",
  "You should be lucky to get my germs."
  "It's been a long day, *wink* *wink*."
  "What do you mean they don't have enough sex?"
  "You have to rotate it around when you do it."
  "I might get a half inch in and then I'm done. It's just fat from there but I'm still done.",
  "It's not because I'm a wizard, it's because you're a little bit nervous.",
  "New fetish",
  "Next week you'll be able to pee.",
  "Just the other day, Kion was telling me he can't pee when other guys are watching",
  "As long as I let you eat I don't have to let you leave this room.",
  "The last time a kid did that I can't even tell you what happened. You see that? I just did witchcraft on you!",
  "Alireza can't figure it out so he'll be spending lunch with me.",
  "If you were white I'd punish you so much more.",
  "I got so excited I choked on my own saliva",
  "You don't know what to do with that onion, you idiot!",
  "Forget it, we're going back to pedophile.",
  "Have you ever run away with a black slave?",
  "You don't like the carrot, how about the whip?",
  "I will whip you as many times as possible to get the message across.",
  "You suck. Finish them."
  "How about I shove it in your mouth and you tell me what it is.",
  "You can borrow neither my hands nor my pants.",
  "It's impossible for me to be emasculated around you.",
  "No, just shut up.",
  "I can shut all of that down. Lockdown, baby!",
  "Shut the f up! Good idea!",
  "The girls are false.",
  "Who needs a spine?",
  "Let's say I slap Alireza.",
  "You mess with my stuff, I mess with your stuff.",
  "I know how much an electric shock can wake up a kid.",
  "You both suck.",
  "Seizure seizure seizure- miss!",
  "Your cake is actually really good.",
  "I'm not shooting my shots in front of the class and missing.",
  "Nobody likes you. Nobody remembers you. Just go and do your work.",
  "Uh oh, time to decide which parent I love more.",
  "You should just stop that and come here.",
  "Help our oil crisis, Captain Saudi Arabia!",
  "Is your grandmother a terrorist?",
  "You have this confused with democracy, it's actually a dictatorship.",
  "ChineseComradesComeTogether.com",
  "I kill you",
  "You should stop talking before I put you in one of these boxes.",
  "I'm a communist spy, I don't care.",
  "I'm an only child. When I was born my mom said why mess with perfection. It doesn't get any better then this.",
  "Samosas? Where?",
  "Don't say that. I know exactly where you live.",
  "I have a death squad outside your house.",
  "Honey, get that sawed-off shotgun out. Put on the special scope."
];
