export.list = {
  "all": [
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CBOT_MINI-YM1!", "name":"Dow Jones Futures", "id": "2"},
      {"ticker":"TVC-SX5E", "name":"Euro Stoxx 50 Pr", "id": "3"},
      {"ticker":"TVC:​UKX", "name":"FTSE 100", "id": "4"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "5"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "6"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "7"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "8"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "9"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "10"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "11"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "12"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "13"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "14"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "15"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "16"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "17"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "18"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "19"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "20"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "21"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "22"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "23"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "24"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "25"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "26"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "27"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "28"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "29"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "30"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "31"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "32"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "33"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "34"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "35"}
  ],
  "futures": ["1"]
}
