export.list = {
  "all": [
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"Dow Jones Futures", "id": "2"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"},
      {"ticker":"CME-SP1!", "name":"S&P 500 Futures", "id": "1"}
  ],
  "futures": ["1"]
}
